name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake libgtest-dev libboost-all-dev
          sudo apt-get install libgmock-dev
          cd /usr/src/googletest/googlemock/
          sudo mkdir build
          sudo cmake ..
          sudo make
          sudo cp googlemock/*.a /usr/lib

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test
