name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y g++ cmake libgtest-dev libboost-all-dev

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make
          make test